settings:
  title: 'Status Page'
  url: 'https://status.janhouse.lv' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations
  # Min time between KV writes, unless status changes. Helps stay within free tier limits. Default: 60 minutes.
  kvWriteCooldownMinutes: 2

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog # unique identifier
    name: Blog
    description: 'www.janhouse.lv' # default=empty
    url: 'https://www.janhouse.lv/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: media
    name: Media
    url: 'https://media.janhouse.lv'
    method: GET
    expectStatus: 403
    linkable: false

  - id: auth
    name: Auth
    url: 'https://auth.janhouse.lv'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false

  - id: vfa
    name: VFA
    description: 'Very Forward Authorizer'
    url: 'https://vfa.janhouse.lv'
    method: GET
    expectStatus: 200
    linkable: true

  - id: git
    name: Git
    url: 'https://git.janhouse.lv'
    method: GET
    expectStatus: 200
    linkable: true